name: halo_alert
description: 'Simple alert dialog for flutter'
version: 0.8.1
repository: https://github.com/HaloWang/halo_alert

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.19.1
  flutter_riverpod: ^2.6.1
  halo: ^0.7.2
  riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
